### ISSUE TITLE
Issues about dataset.

### ISSUE THREAD

**Issue by liren2515** [xiaoxiaoxh/GarmentTracking#1]
Hello,

Thanks for your interesting work and the effort in the collection of the garment data.

I was following the instruction of this [link](https://huggingface.co/datasets/robotflow/vr-folding) to download the dataset. But when I ran `cat folding_dataset.z*  > folding_dataset.zip`, I got the following output from the terminal:
```
cat: folding_dataset.zip: input file is output file
```

Then I ignored it and ran `unzip folding_dataset.zip`, it prompted 
```
Archive:  folding_dataset.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of folding_dataset.zip or
        folding_dataset.zip.zip, and cannot find folding_dataset.zip.ZIP, period.
```

Could you give some insights about how to solve it?

**Comment by xiaoxiaoxh** [comment]
Hi, the `cat` operation should not be executed for multiple times. Maybe you can try another filename (e.g. `cat folding_dataset.z*  > folding_dataset_final.zip`) .

**Comment by liren2515** [comment]
Using `cat folding_dataset.z*  > folding_dataset_final.zip` still gives me error when unzipping it. But I find using `zip -FF folding_dataset.zip --out folding_dataset_final_new.zip` solves this problem.

Another question is about *pc_sim_rgb* and *pc_cls*. I noticed that in the visualization code, *pc_sim_rgb* indicates RGB of input partial point cloud and *pc_cls* indicates classification label of input partial point cloud. What does the RGB value for the point mean? I can't find more explanation about it from the paper or the code. As for the classification label, does it refer to the mask label as shown in Fig. 1(c), where the cloth, hands and background are labeled with different values?

**Comment by xiaoxiaoxh** [comment]
During the generation process of the dataset, we rendered these garments with simple textures. The RGB value comes from the multi-view RGB-D images rendered with Unity, and these RGB-D images will be converted to partial point clouds with RGB colors. `pc_cls` indicates mask labels, which tells you which part of the point cloud is foreground or background.

**Comment by liren2515** [comment]
Hello, I noticed that there is a *scale* item for each garment, which is a scalar. If I understand correctly, this *scale* is used to normalize the raw cloth3d garment mesh, right? I mean as long as I multiply *cloth_nocs_verts* by *scale*, I will have the garment with the same size as the raw garment, right?

What about the offset? How do you decide the center of NOCS?

**Comment by xiaoxiaoxh** [comment]
Yes, this scale is used to normalize the raw cloth3d garment mesh. Actually, we use a fixed scale and offset for all garment instances in the same category. We traversed all the garments in one category and calculate the category-level max-scale and mean centers.  In our data processing code, the NOCS coordinates for raw CLOTH3D mesh vertices are calculated as follows:
`mesh_raw_nocs = (mesh_raw_vertices - category_center) / cate_scale_factor + np.array([0.5, 0.5, 0.5])`
