### ISSUE TITLE
How to get the mesh from the inference result?

### ISSUE THREAD

**Issue by liren2515** [xiaoxiaoxh/GarmentTracking#2]
Hello, 

I want to know how to get the mesh from the inference results produced by `predict_tracking_gt.py`. I looked into the code, but didn't find any clue.

**Comment by xiaoxiaoxh** [comment]
You can reconstruct mesh via `get_task_mesh_vis()` in `eval_tracking.py` after prediction with `predict_tracking_gt.py`.
