### ISSUE TITLE
Pretrained models of Garmentnets on VR-Folding.

### ISSUE THREAD

**Issue by liren2515** [xiaoxiaoxh/GarmentTracking#4]
Hello, sorry for reaching out again. I would like to inquire if it is possible to obtain the pretrained Garmentnets model trained on VR-Folding. I am working on a related project and would like to perform a comparative analysis. But, I find it is not so straightforward to use the VR-Folding data for training Garmentnets.

**Comment by xiaoxiaoxh** [comment]
Hi, I have added a dataloader (dataset) class for GarmentNets [here](https://github.com/xiaoxiaoxh/GarmentTracking/blob/master/datasets/static_dataset.py). You can use this for training GarmentNets on VR-Folding dataset.

**Comment by liren2515** [comment]
Thanks for your help!
